FROM ubuntu AS construye

RUN apt update
RUN apt-get install -y maven openjdk-8-jdk

COPY . .

RUN mvn verify
FROM openjdk:8-jre-alpine
COPY --from=construye /target /target


CMD ["java","-Xmx8m","-Xms8m","-jar","target/words.jar"]
EXPOSE 8080